### ISSUE TITLE
Q about theory

### ISSUE THREAD

**Issue by TwiceMao** [SJTU-ViSYS/SLAM_Evaluation#1]
@LeeBY68 
I'm not sure if I understand correctly. Did you first align the translation part between the estimated poses and the ground truth poses as a whole using the Umeyama method in EVO? When using EVO, the Umeyama method outputs a similarity transformation, and you only used the translation-related part, neglecting the rotation part. Then, you solved the alignment of the rotation part between the estimated poses and the ground truth poses using your own method. Could you please explain how you aligned the rotation part?

**Comment by LeeBY68** [comment]
No.

The first step will align **both roration & translation** estimated from raw EVO (i.e., Umeyama results). But this result can only guarantee **the estimated position** is close to **the GT position**, as shown in the first figure of the readme. (suggesting doing a little test when estimation has a completely different global coordinate compared with the GT coordinate.)

The second step aligns the rotation of each position to make sure the RPE estimation is under the same local coordinate.

**Comment by TwiceMao** [comment]
@LeeBY68  Thx!!!  But I still want to ask, according to what you said before, the second step is to align the rotation part, in order to calculate the RPE related to the rotation. Why not directly compute the rotated APE after aligning the rotation component? This also helps maintain consistency with the error calculation of the pose's translation component. Are there any potential issues with this approach?
Furthermore, even if no alignment method is applied during the calculation of rotated RPE, employing EVO directly can still yield reasonable results for RPE calculation.  So why is it necessary to align the rotation component, as you do, before calculating the RPE of rotation?

Maybe I missed it. I noticed that in your paper, you only compared the performance of different methods in terms of pose **translation**, and did not seem to compare **rotation-related** metrics APE or RPE.

**Comment by TwiceMao** [comment]
@LeeBY68  hi，could you help me with the above questions? I would like to offer my sincere thanks here.

**Comment by LeeBY68** [comment]
Hi @TwiceMao,

1. As I mentioned in this repository and the TextSLAM repository, the additional alignment does not affect APE results. You can certainly use the aligned estimation for APE evaluation and achieve the same results as with the non-aligned estimation. 
2. Without the additional alignment, your RPE evaluation will be completely inaccurate (e.g., correct RPE after additional alignment: ~2cm vs. incorrect RPE without additional alignment: ~1m), leading to erroneous results regardless of whether you compare the translation or rotation components. 

The reason why the additional alignment only affects RPE instead of APE, and why it is necessary for RPE, can be found in the mathematical explanation at: [link to the mathmatic part](https://github.com/MichaelGrupp/evo/blob/master/notebooks/metrics.py_API_Documentation.ipynb)

I suggest testing with a sample dataset to gain a clearer understanding of the tool.

**Comment by TwiceMao** [comment]
@LeeBY68  OK, thanks!
